server.servlet-path: /api/v1
spring:
  application.name: soccer-service
  datasource:
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/soccer_service?createDatabaseIfNotExist=true&useSSL=false"
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialectddialect: org.hibernate.dialect.MySQLInnoDBDialect
      org.envers.audit_table_suffix: "_audit_log"
  resources:
    chain.strategy.content:
      enabled: true
      paths: /**
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false
    default-property-inclusion: non_absent
  http.encoding.force: true

endpoints:
  enabled: true
  sensitive: false

liquibase.change-log: "classpath:liquibase/list.xml"