server.port: 8888
spring:
  application.name: config-server
  cloud.config:
    server.git.uri: "https://github.com/privettoli/microservices-config-files.git"  
    allowOverride: true
    overrideNone: false
    overrideSystemProperties: true
